version: '3.4'

services:
  webapplication1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webapplication2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webapplication3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"